package igu;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;



/**
 *
 * @author Melqui Erazo
 */
public class Pantalla extends javax.swing.JFrame {

    /**
     * Creates new form Pantalla
     */
    private String[][] matriz;
    private String[][] espanol_italiano;
    private String[][] espanol_frances;
    mensaje creado = new mensaje();
    NoFound Nofound = new NoFound();
    vacio Vacio = new vacio();
    public Pantalla() {
        matriz =leerArchivoAMatriz("src/main/resources/traducciones.txt");
        espanol_frances=leerArchivoAMatriz("src/main/resources/español_frances.txt");
        espanol_italiano=leerArchivoAMatriz("src/main/resources/español_italiano.txt");
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        menu_op = new javax.swing.JComboBox<>();
        Boton_Continuar = new javax.swing.JButton();
        agregar = new javax.swing.JPanel();
        label2 = new java.awt.Label();
        Palabra_origen = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        idioma_traduccion = new javax.swing.JComboBox<>();
        Boton_Agregar = new javax.swing.JButton();
        Boton_Limpiar2 = new javax.swing.JButton();
        Palabra_traducida = new javax.swing.JTextField();
        consulta = new javax.swing.JPanel();
        label3 = new java.awt.Label();
        Palabra = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        idioma_origen = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        idioma_destino = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        Boton_Traducir = new javax.swing.JButton();
        Boton_Limpiar = new javax.swing.JButton();
        traduccion = new javax.swing.JTextField();
        conteo = new javax.swing.JPanel();
        label4 = new java.awt.Label();
        numeroINGLES = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        numeroFRANCES = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        numeroITALIANO = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 720));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lirbos_3_1.png"))); // NOI18N

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setFont(new java.awt.Font("Segoe UI Semibold", 3, 36)); // NOI18N
        label1.setMinimumSize(new java.awt.Dimension(40, 40));
        label1.setText("TRADUCTOR");

        menu_op.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Consultar", "Agregar palabra", "Palabras totales" }));

        Boton_Continuar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Boton_Continuar.setText("Continuar");
        Boton_Continuar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Boton_Continuar.setBorderPainted(false);
        Boton_Continuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_ContinuarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(menu_op, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(Boton_Continuar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 53, Short.MAX_VALUE))
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menu_op, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Boton_Continuar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label2.setAlignment(java.awt.Label.CENTER);
        label2.setFont(new java.awt.Font("Segoe UI Semibold", 3, 36)); // NOI18N
        label2.setMinimumSize(new java.awt.Dimension(40, 40));
        label2.setText("Agregar Palabra");

        Palabra_origen.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Palabra_origen.setToolTipText("Escribe la palabra con mayuscula incial");
        Palabra_origen.setActionCommand("<Not Set>");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Palabra en Español");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Palabra Traducida");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Idioma Traducción");

        idioma_traduccion.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        idioma_traduccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Inglés", "Francés", "Italiano" }));

        Boton_Agregar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Boton_Agregar.setText("Agregar");
        Boton_Agregar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Boton_Agregar.setBorderPainted(false);
        Boton_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_AgregarActionPerformed(evt);
            }
        });

        Boton_Limpiar2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Boton_Limpiar2.setText("Limpiar");
        Boton_Limpiar2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Boton_Limpiar2.setBorderPainted(false);
        Boton_Limpiar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Limpiar2ActionPerformed(evt);
            }
        });

        Palabra_traducida.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Palabra_traducida.setToolTipText("Escribe la palabra con mayuscula incial");
        Palabra_traducida.setActionCommand("<Not Set>");

        javax.swing.GroupLayout agregarLayout = new javax.swing.GroupLayout(agregar);
        agregar.setLayout(agregarLayout);
        agregarLayout.setHorizontalGroup(
            agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agregarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Palabra_origen)
                    .addComponent(jLabel2))
                .addGap(12, 12, 12)
                .addGroup(agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Palabra_traducida, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(idioma_traduccion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Boton_Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Boton_Limpiar2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(191, 191, 191))
            .addGroup(agregarLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        agregarLayout.setVerticalGroup(
            agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agregarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(agregarLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Palabra_origen, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(agregarLayout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Boton_Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Boton_Limpiar2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(idioma_traduccion, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(agregarLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48))
                            .addComponent(Palabra_traducida, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        label3.setAlignment(java.awt.Label.CENTER);
        label3.setFont(new java.awt.Font("Segoe UI Semibold", 3, 36)); // NOI18N
        label3.setMinimumSize(new java.awt.Dimension(40, 40));
        label3.setText("Consultar Traducción");

        Palabra.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Palabra.setToolTipText("Escribe la palabra con mayuscula incial");
        Palabra.setActionCommand("<Not Set>");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Palabra");

        idioma_origen.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        idioma_origen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Inglés", "Español", "Francés", "Italiano" }));
        idioma_origen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idioma_origenActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Idioma Origen");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Idioma Destino");

        idioma_destino.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        idioma_destino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Inglés", "Español", "Francés", "Italiano" }));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Traducción");

        Boton_Traducir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Boton_Traducir.setText("Traducir");
        Boton_Traducir.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Boton_Traducir.setBorderPainted(false);
        Boton_Traducir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_TraducirActionPerformed(evt);
            }
        });

        Boton_Limpiar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Boton_Limpiar.setText("Limpiar");
        Boton_Limpiar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Boton_Limpiar.setBorderPainted(false);
        Boton_Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_LimpiarActionPerformed(evt);
            }
        });

        traduccion.setEditable(false);
        traduccion.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        traduccion.setToolTipText("Escribe la palabra con mayuscula incial");
        traduccion.setActionCommand("<Not Set>");

        javax.swing.GroupLayout consultaLayout = new javax.swing.GroupLayout(consulta);
        consulta.setLayout(consultaLayout);
        consultaLayout.setHorizontalGroup(
            consultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultaLayout.createSequentialGroup()
                .addGroup(consultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(consultaLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(consultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Palabra, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(consultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idioma_origen, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(consultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idioma_destino, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(consultaLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(consultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(traduccion)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(Boton_Traducir, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Boton_Limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );
        consultaLayout.setVerticalGroup(
            consultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(consultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(consultaLayout.createSequentialGroup()
                        .addGroup(consultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(consultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(idioma_origen, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                            .addComponent(Palabra)))
                    .addGroup(consultaLayout.createSequentialGroup()
                        .addGroup(consultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(consultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(consultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(idioma_destino, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(traduccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(consultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Boton_Traducir, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Boton_Limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        label4.setAlignment(java.awt.Label.CENTER);
        label4.setFont(new java.awt.Font("Segoe UI Semibold", 3, 36)); // NOI18N
        label4.setMinimumSize(new java.awt.Dimension(40, 40));
        label4.setText("Conteo de Traducciones");

        numeroINGLES.setEditable(false);
        numeroINGLES.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        numeroINGLES.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        numeroINGLES.setText("5");
        numeroINGLES.setToolTipText("Escribe la palabra con mayuscula incial");
        numeroINGLES.setActionCommand("<Not Set>");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Inglés");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Francés");

        numeroFRANCES.setEditable(false);
        numeroFRANCES.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        numeroFRANCES.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        numeroFRANCES.setText("4");
        numeroFRANCES.setToolTipText("Escribe la palabra con mayuscula incial");
        numeroFRANCES.setActionCommand("<Not Set>");
        numeroFRANCES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroFRANCESActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Italiano");

        numeroITALIANO.setEditable(false);
        numeroITALIANO.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        numeroITALIANO.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        numeroITALIANO.setText("8");
        numeroITALIANO.setToolTipText("Escribe la palabra con mayuscula incial");
        numeroITALIANO.setActionCommand("<Not Set>");

        javax.swing.GroupLayout conteoLayout = new javax.swing.GroupLayout(conteo);
        conteo.setLayout(conteoLayout);
        conteoLayout.setHorizontalGroup(
            conteoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(conteoLayout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(numeroINGLES, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numeroFRANCES, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numeroITALIANO, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(336, 336, 336))
            .addGroup(conteoLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        conteoLayout.setVerticalGroup(
            conteoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(conteoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(conteoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(conteoLayout.createSequentialGroup()
                        .addGroup(conteoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(conteoLayout.createSequentialGroup()
                                .addComponent(numeroFRANCES, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addGap(2, 2, 2))
                            .addComponent(numeroINGLES)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(73, 73, 73))
                    .addGroup(conteoLayout.createSequentialGroup()
                        .addGroup(conteoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(numeroITALIANO, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(consulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(conteo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(agregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(consulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(agregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(conteo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_ContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_ContinuarActionPerformed
        if("Consultar".equals(menu_op.getSelectedItem()) ){
            menu.setVisible(true);
            agregar.setVisible(false);
            consulta.setVisible(true);
            conteo.setVisible(false);
        } else { if("Agregar palabra".equals(menu_op.getSelectedItem())){
            menu.setVisible(true);
            agregar.setVisible(true);
            consulta.setVisible(false);
            conteo.setVisible(false);
        } else { if("Palabras totales".equals(menu_op.getSelectedItem())){
            //contar palabras idiomas
            int numeroingles = matriz.length;
            int numeroitaliano = espanol_italiano.length;
            int numerofrances = espanol_frances.length;
            numeroINGLES.setText(String.valueOf(numeroingles));
            numeroFRANCES.setText(String.valueOf(numerofrances));
            numeroITALIANO.setText(String.valueOf(numeroitaliano));


            menu.setVisible(true);
            agregar.setVisible(false);
            consulta.setVisible(false);
            conteo.setVisible(true);
        } else{
            agregar.setVisible(false);
            consulta.setVisible(false);
            conteo.setVisible(false);
        }
        }
        }
    }//GEN-LAST:event_Boton_ContinuarActionPerformed

    private void Boton_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_AgregarActionPerformed
String palabraOrigen = Palabra_origen.getText();
    String palabraTraducida = Palabra_traducida.getText();
    String idiomaDestino = (String) idioma_traduccion.getSelectedItem();
    //mensaje de confirmar creacion
    creado.setVisible(true);
    creado.setLocationRelativeTo(null);
    //se actualizan las matrices
    matriz =leerArchivoAMatriz("src/main/resources/traducciones.txt");
    espanol_frances=leerArchivoAMatriz("src/main/resources/español_frances.txt");
    espanol_italiano=leerArchivoAMatriz("src/main/resources/español_italiano.txt");

    if (!palabraOrigen.isEmpty() && !palabraTraducida.isEmpty() && !idiomaDestino.equals("...")) {
        // Obtener la ruta del archivo según el idioma de destino
        String rutaArchivo = obtenerRutaArchivo(idiomaDestino);

        if (rutaArchivo != null) {
            try (BufferedWriter bw = new BufferedWriter(new FileWriter(rutaArchivo, true))) {
                // Escribir en el archivo la traducción
                bw.write(palabraOrigen + "," + idiomaDestino + "," + palabraTraducida);
                bw.newLine();
                System.out.println("Palabra guardada correctamente.");
            } catch (IOException e) {
                System.err.println("Error al guardar la palabra: " + e.getMessage());
            }
        } else {
            System.out.println("No se encontró una ruta válida para el idioma seleccionado.");
        }
    } else {
        System.out.println("Por favor, complete todos los campos.");
        Vacio.setVisible(true);
        Vacio.setLocationRelativeTo(null);
    }
    }//GEN-LAST:event_Boton_AgregarActionPerformed

    private void Boton_Limpiar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Limpiar2ActionPerformed
        Palabra_origen.setText("");
        Palabra_traducida.setText("");
        idioma_traduccion.setSelectedIndex(0);
    }//GEN-LAST:event_Boton_Limpiar2ActionPerformed

    private void Boton_TraducirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_TraducirActionPerformed
        // TODO add your handling code here:
            String palabraIngresada = Palabra.getText();
    String idiomaDestinoSeleccionado = (String) idioma_destino.getSelectedItem();
    String idiomaOrigenSeleccionado = (String) idioma_origen.getSelectedItem();
    
    if (palabraIngresada.isEmpty() || idiomaDestinoSeleccionado.equals("...")) {
        traduccion.setText("");
        Vacio.setVisible(true);
        Vacio.setLocationRelativeTo(null);
    } else {String resultado = buscarTraduccion(palabraIngresada, idiomaDestinoSeleccionado, idiomaOrigenSeleccionado);
    traduccion.setText(resultado);}
    }//GEN-LAST:event_Boton_TraducirActionPerformed

    private void Boton_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_LimpiarActionPerformed
        Palabra.setText("");
        idioma_origen.setSelectedItem(idioma_origen.getItemAt(0));
        idioma_destino.setSelectedIndex(0);
        traduccion.setText("");
    }//GEN-LAST:event_Boton_LimpiarActionPerformed

    private void idioma_origenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idioma_origenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idioma_origenActionPerformed

    private void numeroFRANCESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroFRANCESActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroFRANCESActionPerformed
    // al iniciar se ocultan los contenedores
    public void ocultarLabel() {
    consulta.setVisible(false);
    agregar.setVisible(false);
    conteo.setVisible(false);
    }


//buscar traduccion
private String buscarTraduccion(String palabra, String idiomaDestino, String idiomaOrigen) {
    String palabra_temp = null;
    if(idiomaOrigen.equals("Español") && idiomaDestino.equals("Inglés") ){
    for (String[] traduccion : matriz ) {
        if (traduccion[0].equalsIgnoreCase(palabra) && traduccion[1].equalsIgnoreCase(idiomaDestino)) {
            return traduccion[2];
        }
    }
      
    } else { if(idiomaOrigen.equals("Español") && idiomaDestino.equals("Italiano") ){
        for (String[] traduccion : espanol_italiano ) {
        if (traduccion[0].equalsIgnoreCase(palabra) && traduccion[1].equalsIgnoreCase(idiomaDestino)) {
            return traduccion[2];
        }
    }
    } else { if(idiomaOrigen.equals("Español") && idiomaDestino.equals("Francés")){
    for (String[] traduccion : espanol_frances ) {
        if (traduccion[0].equalsIgnoreCase(palabra) && traduccion[1].equalsIgnoreCase(idiomaDestino)) {
            return traduccion[2];
        }
    }
    }} } //ingles-italiano
    if(idiomaOrigen.equals("Inglés") && idiomaDestino.equals("Italiano") ){
        
        for (String [] traduccion : matriz ) {
        if (traduccion[2].equalsIgnoreCase(palabra) && traduccion[1].equalsIgnoreCase("Inglés")) {
            palabra_temp = traduccion[0];
        }
    }
        for (String [] traduccion : espanol_italiano ) {
        if (traduccion[0].equalsIgnoreCase(palabra_temp) && traduccion[1].equalsIgnoreCase(idiomaDestino)) {
            return traduccion[2];
        }
    }
        
    } //traducir ingles-frances
    if(idiomaOrigen.equals("Inglés") && idiomaDestino.equals("Francés") ){
        
        for (String [] traduccion : matriz ) {
        if (traduccion[2].equalsIgnoreCase(palabra) && traduccion[1].equalsIgnoreCase("Inglés")) {
            palabra_temp = traduccion[0];
        }
    }
        for (String [] traduccion : espanol_frances ) {
        if (traduccion[0].equalsIgnoreCase(palabra_temp) && traduccion[1].equalsIgnoreCase(idiomaDestino)) {
            return traduccion[2];
        }
    }
    }
    // traducir ingles-español
    if(idiomaOrigen.equals("Inglés") && idiomaDestino.equals("Español") ){
    for (String[] traduccion : matriz ) {
        if (traduccion[2].equalsIgnoreCase(palabra) && traduccion[1].equalsIgnoreCase("Inglés")) {
            return traduccion[0];
        }
    } 
    }
    //traducir frances-ingles
    if(idiomaOrigen.equals("Francés") && idiomaDestino.equals("Inglés") ){
        
        for (String [] traduccion : espanol_frances ) {
        if (traduccion[2].equalsIgnoreCase(palabra) && traduccion[1].equalsIgnoreCase("Francés")) {
            palabra_temp = traduccion[0];
        }
    }
        for (String [] traduccion : matriz ) {
        if (traduccion[0].equalsIgnoreCase(palabra_temp) && traduccion[1].equalsIgnoreCase(idiomaDestino)) {
            return traduccion[2];
        }
    } 
    }
    //traducir frances-italiano
    if(idiomaOrigen.equals("Francés") && idiomaDestino.equals("Italiano") ){
        
        for (String [] traduccion : espanol_frances ) {
        if (traduccion[2].equalsIgnoreCase(palabra) && traduccion[1].equalsIgnoreCase("Francés")) {
            palabra_temp = traduccion[0];
        }
    }
        for (String [] traduccion : espanol_italiano ) {
        if (traduccion[0].equalsIgnoreCase(palabra_temp) && traduccion[1].equalsIgnoreCase(idiomaDestino)) {
            return traduccion[2];
        }
    } 
    }
    //traducir frances-español
    if(idiomaOrigen.equals("Francés") && idiomaDestino.equals("Español") ){
      for (String[] traduccion : espanol_frances) {
        if (traduccion[2].equalsIgnoreCase(palabra) && traduccion[1].equalsIgnoreCase("Francés")) {
            return traduccion[0];
        }
    } 
    }
    //traducir italiano-frances
    if(idiomaOrigen.equals("Italiano") && idiomaDestino.equals("Francés") ){
        
        for (String [] traduccion : espanol_italiano ) {
        if (traduccion[2].equalsIgnoreCase(palabra) && traduccion[1].equalsIgnoreCase("Italiano")) {
            palabra_temp = traduccion[0];
        }
    }
        for (String [] traduccion : espanol_frances ) {
        if (traduccion[0].equalsIgnoreCase(palabra_temp) && traduccion[1].equalsIgnoreCase(idiomaDestino)) {
            return traduccion[2];
        }
    } 
    }
    //traducir italiano-ingles
    if(idiomaOrigen.equals("Italiano") && idiomaDestino.equals("Inglés") ){
        
        for (String [] traduccion : espanol_italiano ) {
        if (traduccion[2].equalsIgnoreCase(palabra) && traduccion[1].equalsIgnoreCase("Italiano")) {
            palabra_temp = traduccion[0];
        }
    }
        for (String [] traduccion : matriz ) {
        if (traduccion[0].equalsIgnoreCase(palabra_temp) && traduccion[1].equalsIgnoreCase(idiomaDestino)) {
            return traduccion[2];
        }
    } 
    }
    //traducir italiano-español
    if(idiomaOrigen.equals("Italiano") && idiomaDestino.equals("Español") ){
      for (String[] traduccion : espanol_italiano) {
        if (traduccion[2].equalsIgnoreCase(palabra) && traduccion[1].equalsIgnoreCase("Italiano")) {
            return traduccion[0];
        }
    } 
    }
    Nofound.setVisible(true);
    Nofound.setLocationRelativeTo(null);
    return "";
}
public static String[][] leerArchivoAMatriz(String rutaArchivo) {
        ArrayList<String[]> listaTemporal = new ArrayList<>();
        try (BufferedReader br = new BufferedReader(new FileReader(rutaArchivo))) {
            String linea;
            while ((linea = br.readLine()) != null) {
                // Dividir cada línea por la coma
                String[] traduccion = linea.split(",");
                listaTemporal.add(traduccion);
            }
        } catch (IOException e) {
            e.printStackTrace();
        }

        // Convertir la lista en una matriz
        String[][] matriz = new String[listaTemporal.size()][3];
        return listaTemporal.toArray(matriz);
    }
//  aqui se define la funcion para permitir guardar palabras
public static void guardarPalabra(String palabraOrigen, String palabraTraducida, String idiomaDestino) throws IOException {
        String rutaArchivo = obtenerRutaArchivo(idiomaDestino);

        if (rutaArchivo == null) {
            System.out.println("Idioma no soportado.");
            return;
        }

        try (BufferedWriter bw = new BufferedWriter(new FileWriter(rutaArchivo, true))) {
            bw.write(palabraOrigen + "," + idiomaDestino + "," + palabraTraducida);
            bw.newLine();
            System.out.println("Palabra guardada correctamente.");
        }    }

    private static String obtenerRutaArchivo(String idiomaDestino) {
        switch (idiomaDestino.toLowerCase()) {
            case "inglés":
                return "src/main/resources/traducciones.txt";
            case "francés":
                return "src/main/resources/español_frances.txt";
            case "italiano":
                return "src/main/resources/español_italiano.txt";
            default:
                return null;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Agregar;
    private javax.swing.JButton Boton_Continuar;
    private javax.swing.JButton Boton_Limpiar;
    private javax.swing.JButton Boton_Limpiar2;
    private javax.swing.JButton Boton_Traducir;
    private javax.swing.JTextField Palabra;
    private javax.swing.JTextField Palabra_origen;
    private javax.swing.JTextField Palabra_traducida;
    private javax.swing.JPanel agregar;
    private javax.swing.JPanel consulta;
    private javax.swing.JPanel conteo;
    private javax.swing.JComboBox<String> idioma_destino;
    private javax.swing.JComboBox<String> idioma_origen;
    private javax.swing.JComboBox<String> idioma_traduccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private javax.swing.JPanel menu;
    private javax.swing.JComboBox<String> menu_op;
    private javax.swing.JTextField numeroFRANCES;
    private javax.swing.JTextField numeroINGLES;
    private javax.swing.JTextField numeroITALIANO;
    private javax.swing.JTextField traduccion;
    // End of variables declaration//GEN-END:variables
}
